### ISSUE TITLE
JWASMD produces screen garbage on EGA

### ISSUE THREAD

**Issue by boeckmann** [Baron-von-Riedesel/JWasm#16]
At least I encountered this when running in DosBox. JWASMR runs fine.
![command_000](https://user-images.githubusercontent.com/6333969/226435199-2e6c3176-de58-4e5f-b7a5-97fccfd177c3.png)

**Comment by Baron-von-Riedesel** [comment]
No idea what's the cause. jwasmd uses the hx dos extender - AFAIR this extender is compatible with DosBox.

**Comment by Baron-von-Riedesel** [comment]
I guess with "on EGA" means "machine=ega" in dosbox.conf?

Well, I tried jwasmd.exe with that setting and couldn't find any problems.
