### ISSUE TITLE
JWASMD refuses to overwrite existing file

### ISSUE THREAD

**Issue by boeckmann** [Baron-von-Riedesel/JWasm#17]
At least under DosBox JWASMD refuses to overwrite an existing .OBJ file. JWASMR and the original WASM have no problems with it. Is that perhaps some incompatibility between the DOS extender and DosBox?
![command_001](https://user-images.githubusercontent.com/6333969/226440653-a5e1d04a-7370-4de2-8a62-46e6679c21f4.png)

**Comment by Baron-von-Riedesel** [comment]
> Is that perhaps some incompatibility between the DOS extender and DosBox?

Miost likely. jwasm.exe uses LFN if available, and this requires that DOS returns the correct error code and carry flag if it's not isupported.

**Comment by boeckmann** [comment]
Worked around it by building a 32-bit DOS4G/W version of 2.17 by misusing a slightly modified OWOS2.mak makefile. Was able to build it under Open Watcom 1.9 DOS. I do not know if this build is LFN enabled, but I do not need it anyway. The DOS4G/W executable also fixes my EGA problem.

**Comment by Baron-von-Riedesel** [comment]
JWasmD v2.18 uses the "standard" OW 2.0 DOS extended modules - so this issue should be fixed now.
