### ISSUE TITLE
Missing cstrtwhx.obj?

### ISSUE THREAD

**Issue by ASMHSE** [Baron-von-Riedesel/JWasm#21]
Triyng to build JWasmD with OWWin32.mak:

             Error! E2008: cannot open cstrtwhx.obj : No such file or directory

**Comment by Baron-von-Riedesel** [comment]
I see - will be fixed.

If you like, you can get the file from the HXDEV package ( sub dir OWSupp/DOS )  [https://github.com/Baron-von-Riedesel/HX/releases/download/v2.20/HXDEV220.zip](url)

**Comment by ASMHSE** [comment]
A couple of days after the post I found your HXDEV in other place, and works OK. 

Anyway is very confusing.  

Thanks.
