### ISSUE TITLE
Question: how to generate non-sign-extended encoding?

### ISSUE THREAD

**Issue by boeckmann** [Baron-von-Riedesel/JWasm#26]
ADD AX,0FFFFh et. al. get encoded like 83C0FF instead of 05FFFF. So it encodes the sign-extended imm8 operand version instead of the imm16 one.

Is there a way to force JWasm to use the latter encoding (other than creating e.g. a macro)? I am currently converting the EDR-DOS source from RASM86 to JWasm, and this makes equivalence test between the two outputs harder than it has to be, because RASM86 encodes as ADD AX,imm16. This also affects the other arithmitic instructions where sign-extension can be applied.

**Comment by Baron-von-Riedesel** [comment]
> Is there a way to force JWasm to use the latter encoding 

"add ax, word ptr 0ffffh" should work. The Masm docs call that "type coercion".

**Comment by boeckmann** [comment]
Thanks, this works :)
