### ISSUE TITLE
Differences from the original JWasm?

### ISSUE THREAD

**Issue by luizfernandonb** [Baron-von-Riedesel/JWasm#28]
@Baron-von-Riedesel, what is the difference between your repository and the "original" one? (https://github.com/JWasm/JWasm)

**Comment by Baron-von-Riedesel** [comment]
> what is the difference between your repository and the "original" one? (https://github.com/JWasm/JWasm)

I guess https://github.com/JWasm/JWasm is just a clone of the old JWasm on SF (https://sourceforge.net/projects/jwasm/).
