### ISSUE TITLE
lea edx,[esp + type(edx)]

### ISSUE THREAD

**Issue by nidud** [Baron-von-Riedesel/JWasm#3]
http://masm32.com/board/index.php?topic=6117.msg65190#msg65190
```
    .386
    .model flat
    .code

    lea edx,[esp + type edx ]
    lea edx,[esp + type(edx)]

    end

```

**Comment by Baron-von-Riedesel** [comment]
that's an interesting find. the expression evaluator really has become a mess. Hopefully you have cleaned this up in your fork?!

Will be fixed in next prerelease.

**Comment by nidud** [comment]
It's written in assembly now so there has been some changes there. However the main problem (or mess) was all the changes already made, accumulating a lot of comments and ifdefs which makes it very hard to read.

I changed some of the keywords used so it's called TYPEOF now. There is also a merger of PROC and MACRO going on so INVOKE may be used to sort out arguments for a MACRO.
