### ISSUE TITLE
Asm causing real-mode compiler to hang

### ISSUE THREAD

**Issue by VaKonS** [Baron-von-Riedesel/JWasm#9]
The attached file "e.asm" ([errorasm.zip](https://github.com/Baron-von-Riedesel/JWasm/files/5358924/errorasm.zip), 2 kb) hangs real-mode version of compiler.
Also, JWasm once displayed "internal error in file omfint.c, line 168" message, but I can not get this error anymore, it simply hangs.

The file is currently in compilable form, but if you remove file "dummy.asm" (or make any error in "e.asm"), the compiler will hang.

It also hangs in DosBox (as in safer environment), but only after several launches and if free memory is below ≈600 kb.
The attached "a.bat" automatically eats memory and launches JWasmr.exe to reproduce the error (in DosBox the bat needs to be relaunched manually, because its command.com does not support /k switch).

The error only affects real-mode version, therefore it is probably a limitation of low memory, but if you'll decide to look, here it is.
And thanks for the program!

**Comment by VaKonS** [comment]
"DosBox-compatible" variant: [asm_hang.zip](https://github.com/Baron-von-Riedesel/JWasm/files/5360890/asm_hang.zip) (334 kb).

1) Run "a.bat", JWasm will compile until there is enough memory, and it *will not hang*.
2) To produce error, delete "dummy.asm" and run "a.bat". JWasmr.exe will hang.

**Comment by Baron-von-Riedesel** [comment]
Thanks, I can reproduce the hang. 

It's indeed a malloc/free issue; memory management in the real-mode version differs from the protected-mode versions.

**Comment by Baron-von-Riedesel** [comment]
should be fixed now.

**Comment by VaKonS** [comment]
Thank you so much, it works perfectly now!
